version: "3.8"

services:
    db:
        container_name: bodyguard-db
        image: postgres:latest
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: bodyguarddb
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/bodyguard/data
        networks:
            - internal
        dns:
            - 8.8.8.8

    engine:
        container_name: bodyguard-engine
        build:
            context: ./engine
            dockerfile: dockerfile
        command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8080"]
        working_dir: /app
        ports:
            - "8080:8080"
        networks:
            - internal
        restart: on-failure
        volumes:
            - ./engine:/app
            - ./engine/config.yaml:/app/config.yaml

networks:
    internal:
        driver: bridge

volumes:
    pgdata: {}