FROM python:latest

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN ls core/model/config.json
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8001"]